### ISSUE TITLE
Error in pop[i] <- as.character(popdat[, 2][popdat[, 1] == ind[i]]) :    replacement has length zero

### ISSUE THREAD

**Issue by tommydevitt** [jinyung/loci2migrate#1]
When I try to run the function I get:

Error in pop[i] <- as.character(popdat[, 2][popdat[, 1] == ind[i]]) : 
  replacement has length zero

Any suggestions?

**Comment by jinyung** [comment]
This line of code tries to match the individual's name in population file to that in the .loci file. The error occurred because it couldn't find a match, most likely due to misspelling in either file. I attempted to fix this in [v0.0.2 release](https://github.com/jinyung/loci2migrate/releases/tag/v0.0.2), it should at least tell you which individual didn't match, may I ask you which version you are using?

**Comment by tommydevitt** [comment]
Thanks. I am using v0.0.2, however.

**Comment by tommydevitt** [comment]
Any progress on this?

**Comment by tommydevitt** [comment]
I did have a label mismatch; my apologies. Thanks for sharing a very useful script.

Tom

**Comment by jinyung** [comment]
quick fix on spelling checking function to include additional scenario, added in commit https://github.com/jinyung/loci2migrate/commit/feb183cd84a278604faa64887389c983f162c9b6
